"""add formation and coach to lineups

Revision ID: 8a05173a120e
Revises: 
Create Date: 2026-02-17 23:42:44.712488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a05173a120e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lineups_match', table_name='lineups')
    op.drop_index('idx_lineups_team', table_name='lineups')
    op.drop_index('idx_lineups_unique', table_name='lineups')
    op.drop_table('lineups')
    op.drop_index('idx_match_statistics_match', table_name='match_statistics')
    op.drop_index('idx_match_statistics_team', table_name='match_statistics')
    op.drop_table('match_statistics')
    op.drop_index('idx_player_statistics_match', table_name='player_statistics')
    op.drop_index('idx_player_statistics_player', table_name='player_statistics')
    op.drop_table('player_statistics')
    op.drop_constraint('unique_event', 'events', type_='unique')
    op.drop_index('idx_teams_external_id', table_name='teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_teams_external_id', 'teams', ['external_id'], unique=True)
    op.create_unique_constraint('unique_event', 'events', ['match_id', 'minute', 'type', 'player_name'])
    op.create_table('player_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('player_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('captain', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('substitute', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('shots_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_on', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goals_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goals_conceded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('saves', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tackles_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tackles_blocks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tackles_interceptions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duels_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duels_won', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dribbles_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dribbles_success', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dribbles_past', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fouls_drawn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fouls_committed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_yellow', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_red', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_won', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_committed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_scored', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_missed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_saved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='player_statistics_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='player_statistics_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='player_statistics_pkey'),
    sa.UniqueConstraint('match_id', 'player_id', name='unique_match_player')
    )
    op.create_index('idx_player_statistics_player', 'player_statistics', ['player_id'], unique=False)
    op.create_index('idx_player_statistics_match', 'player_statistics', ['match_id'], unique=False)
    op.create_table('match_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shots_on_goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_off_goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blocked_shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_inside_box', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_outside_box', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fouls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('corner_kicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('offsides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ball_possession', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yellow_cards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('red_cards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goalkeeper_saves', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_accurate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_percent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='match_statistics_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='match_statistics_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='match_statistics_pkey'),
    sa.UniqueConstraint('match_id', 'team_id', name='unique_match_team_stat')
    )
    op.create_index('idx_match_statistics_team', 'match_statistics', ['team_id'], unique=False)
    op.create_index('idx_match_statistics_match', 'match_statistics', ['match_id'], unique=False)
    op.create_table('lineups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('grid', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('starter', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='lineups_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='lineups_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lineups_pkey')
    )
    op.create_index('idx_lineups_unique', 'lineups', ['match_id', 'team_id', 'player_id'], unique=True)
    op.create_index('idx_lineups_team', 'lineups', ['team_id'], unique=False)
    op.create_index('idx_lineups_match', 'lineups', ['match_id'], unique=False)
    # ### end Alembic commands ###
