"""add_indexes_constraints_and_fix_types

Revision ID: 304c6d16db08
Revises: a1b2c3d4e5f7
Create Date: 2026-03-19 20:04:57.816996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '304c6d16db08'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ix_style_references_event_type')
    op.execute('DROP INDEX IF EXISTS ix_style_references_event_type_instance')
    op.execute('DROP INDEX IF EXISTS ix_style_references_instance')
    op.execute('DROP TABLE IF EXISTS style_references')
    op.execute('DROP TABLE IF EXISTS user_favorites')
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.execute('ALTER TABLE events DROP CONSTRAINT IF EXISTS uq_event')
    op.create_index(op.f('ix_events_match_id'), 'events', ['match_id'], unique=False)
    op.alter_column('lineups', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.execute('ALTER TABLE lineups DROP CONSTRAINT IF EXISTS lineups_match_player_unique')
    op.execute(
        "ALTER TABLE match_statistics ALTER COLUMN possession_percentage "
        "TYPE NUMERIC(5,1) USING possession_percentage::numeric(5,1)"
    )
    op.execute('DROP INDEX IF EXISTS ix_media_clips_vid')
    op.execute('DROP INDEX IF EXISTS idx_media_queue_created_at')
    op.execute('DROP INDEX IF EXISTS idx_media_queue_status')
    op.execute('ALTER TABLE players DROP CONSTRAINT IF EXISTS players_external_id_key')
    op.execute('DROP INDEX IF EXISTS ix_players_external_id')
    op.create_index(op.f('ix_players_external_id'), 'players', ['external_id'], unique=True)
    op.create_index(op.f('ix_standings_team_id'), 'standings', ['team_id'], unique=False)
    op.create_unique_constraint('uq_standing', 'standings', ['season_id', 'competition_id', 'team_id'])
    op.execute('ALTER TABLE standings DROP CONSTRAINT IF EXISTS standings_team_id_fkey')
    op.create_foreign_key(None, 'standings', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.execute('ALTER TABLE synthetic_events DROP CONSTRAINT IF EXISTS uq_synthetic_match_type')
    op.alter_column('ticker_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ticker_entries_match_id'), 'ticker_entries', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_entries_match_id'), table_name='ticker_entries')
    op.alter_column('ticker_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_synthetic_match_type', 'synthetic_events', ['match_id', 'type'])
    op.drop_constraint(None, 'standings', type_='foreignkey')
    op.create_foreign_key('standings_team_id_fkey', 'standings', 'teams', ['team_id'], ['id'])
    op.execute('ALTER TABLE standings DROP CONSTRAINT IF EXISTS uq_standing')
    op.drop_index(op.f('ix_standings_team_id'), table_name='standings')
    op.drop_index(op.f('ix_players_external_id'), table_name='players')
    op.create_index('ix_players_external_id', 'players', ['external_id'], unique=False)
    op.create_unique_constraint('players_external_id_key', 'players', ['external_id'])
    op.create_index('idx_media_queue_status', 'media_queue', ['status'], unique=False)
    op.create_index('idx_media_queue_created_at', 'media_queue', [sa.text('created_at DESC')], unique=False)
    op.create_index('ix_media_clips_vid', 'media_clips', ['vid'], unique=True)
    op.execute(
        "ALTER TABLE match_statistics ALTER COLUMN possession_percentage "
        "TYPE VARCHAR(10) USING possession_percentage::varchar"
    )
    op.create_unique_constraint('lineups_match_player_unique', 'lineups', ['match_id', 'player_id'])
    op.alter_column('lineups', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index(op.f('ix_events_match_id'), table_name='events')
    op.create_unique_constraint('uq_event', 'events', ['match_id', 'time', 'event_type'])
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('user_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='user_favorites_team_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_favorites_pkey'),
    sa.UniqueConstraint('team_id', name='unique_favorite_team')
    )
    op.create_table('style_references',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('match_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('league', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('minute', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extra_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('instance', sa.VARCHAR(length=20), server_default=sa.text("'ef_whitelabel'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='style_references_pkey'),
    sa.UniqueConstraint('match_label', 'minute', 'extra_time', 'event_type', 'text', name='uq_style_ref')
    )
    op.create_index('ix_style_references_instance', 'style_references', ['instance'], unique=False)
    op.create_index('ix_style_references_event_type_instance', 'style_references', ['event_type', 'instance'], unique=False)
    op.create_index('ix_style_references_event_type', 'style_references', ['event_type'], unique=False)
    # ### end Alembic commands ###
