"""refactor_events

Revision ID: 4e123c6bc18e
Revises: 88bbf4ad9988
Create Date: 2026-03-02 15:05:50.229234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e123c6bc18e'
down_revision: Union[str, None] = '88bbf4ad9988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
