"""add_team_category_position_ct_uid

Revision ID: 7f1739cda3fe
Revises: 4e123c6bc18e
Create Date: 2026-03-02 16:50:54.951402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f1739cda3fe'
down_revision: Union[str, None] = '4e123c6bc18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition_teams', sa.Column('uid', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_competition_teams_uid'), 'competition_teams', ['uid'], unique=True)
    op.add_column('teams', sa.Column('category', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('teams', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'position')
    op.drop_column('teams', 'category')
    op.drop_index(op.f('ix_competition_teams_uid'), table_name='competition_teams')
    op.drop_column('competition_teams', 'uid')
    # ### end Alembic commands ###
