"""add icon to ticker_entries

Revision ID: 8d1f02b7b4f5
Revises: 78c2c9832dc9
Create Date: 2026-02-19 23:50:14.426777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d1f02b7b4f5'
down_revision: Union[str, None] = '78c2c9832dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lineups_id', table_name='lineups')
    op.drop_table('lineups')
    op.drop_index('ix_match_statistics_id', table_name='match_statistics')
    op.drop_table('match_statistics')
    op.drop_index('ix_player_statistics_id', table_name='player_statistics')
    op.drop_index('ix_player_statistics_match_id', table_name='player_statistics')
    op.drop_index('ix_player_statistics_player_id', table_name='player_statistics')
    op.drop_table('player_statistics')
    op.drop_constraint('uq_events_match_minute_player_type', 'events', type_='unique')
    op.drop_constraint('unique_teams_external_id', 'teams', type_='unique')
    op.add_column('ticker_entries', sa.Column('icon', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker_entries', 'icon')
    op.create_unique_constraint('unique_teams_external_id', 'teams', ['external_id'])
    op.create_unique_constraint('uq_events_match_minute_player_type', 'events', ['match_id', 'minute', 'player_id', 'type'])
    op.create_table('player_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('player_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('minutes_played', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('captain', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('substitute', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('offsides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_on', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goals_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goals_conceded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goals_assists', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goals_saves', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tackles_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tackles_blocks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tackles_interceptions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duels_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duels_won', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dribbles_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dribbles_success', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dribbles_past', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fouls_drawn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fouls_committed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_yellow', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_red', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_won', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_committed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_scored', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_missed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalty_saved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='player_statistics_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='player_statistics_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='player_statistics_pkey'),
    sa.UniqueConstraint('match_id', 'player_id', name='unique_match_player')
    )
    op.create_index('ix_player_statistics_player_id', 'player_statistics', ['player_id'], unique=False)
    op.create_index('ix_player_statistics_match_id', 'player_statistics', ['match_id'], unique=False)
    op.create_index('ix_player_statistics_id', 'player_statistics', ['id'], unique=False)
    op.create_table('match_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shots_on_goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_off_goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blocked_shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_insidebox', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_outsidebox', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fouls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('corner_kicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('offsides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ball_possession', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yellow_cards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('red_cards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goalkeeper_saves', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_accurate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='match_statistics_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='match_statistics_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='match_statistics_pkey'),
    sa.UniqueConstraint('match_id', 'team_id', name='unique_match_team_stat')
    )
    op.create_index('ix_match_statistics_id', 'match_statistics', ['id'], unique=False)
    op.create_table('lineups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('formation', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coach_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('grid', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_substitute', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='lineups_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='lineups_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lineups_pkey'),
    sa.UniqueConstraint('match_id', 'player_id', name='unique_lineup_player')
    )
    op.create_index('ix_lineups_id', 'lineups', ['id'], unique=False)
    # ### end Alembic commands ###
