"""add_lineup_match_statistic

Revision ID: 982704fc3022
Revises: 5ed595b179c3
Create Date: 2026-02-26 14:51:34.182359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982704fc3022'
down_revision: Union[str, None] = '5ed595b179c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('formation_place', sa.Integer(), nullable=True),
    sa.Column('formation_position', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('number_of_goals', sa.Integer(), nullable=True),
    sa.Column('has_yellow_card', sa.Boolean(), nullable=True),
    sa.Column('has_red_card', sa.Boolean(), nullable=True),
    sa.Column('is_substituted', sa.Boolean(), nullable=True),
    sa.Column('formation', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('possession_percentage', sa.String(length=10), nullable=True),
    sa.Column('total_pass', sa.Integer(), nullable=True),
    sa.Column('accurate_pass', sa.Integer(), nullable=True),
    sa.Column('duel_won', sa.Integer(), nullable=True),
    sa.Column('duel_lost', sa.Integer(), nullable=True),
    sa.Column('air_duel_won', sa.Integer(), nullable=True),
    sa.Column('air_duel_lost', sa.Integer(), nullable=True),
    sa.Column('blocked_pass', sa.Integer(), nullable=True),
    sa.Column('total_offside', sa.Integer(), nullable=True),
    sa.Column('corner_taken', sa.Integer(), nullable=True),
    sa.Column('goal_scoring_attempt', sa.Integer(), nullable=True),
    sa.Column('goal_on_target_scoring_attempt', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('crosses_in_match', sa.Integer(), nullable=True),
    sa.Column('crosses_accurate', sa.Integer(), nullable=True),
    sa.Column('total_crosses', sa.Integer(), nullable=True),
    sa.Column('formation_used', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', name='uq_match_statistic')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_statistics')
    op.drop_table('lineups')
    # ### end Alembic commands ###
