"""add_competition_teams

Revision ID: 999916277edd
Revises: 5474bfd45705
Create Date: 2026-03-02 11:51:23.059848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '999916277edd'
down_revision: Union[str, None] = '5474bfd45705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competition_teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_competition_teams_id'), 'competition_teams', ['id'], unique=False)
    op.alter_column('competitions', 'has_standings_per_matchday',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('competitions', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('competitions', 'position',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('competitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_competitions_external_id', 'competitions', type_='unique')
    op.drop_constraint('uq_competitions_uid', 'competitions', type_='unique')
    op.create_index(op.f('ix_competitions_external_id'), 'competitions', ['external_id'], unique=True)
    op.create_index(op.f('ix_competitions_id'), 'competitions', ['id'], unique=False)
    op.create_index(op.f('ix_competitions_uid'), 'competitions', ['uid'], unique=True)
    op.alter_column('countries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('countries_name_key', 'countries', type_='unique')
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.add_column('matches', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('matches', sa.Column('localized_title', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('is_kickoff_confirmed', sa.Boolean(), nullable=False))
    op.add_column('matches', sa.Column('number_of_goal_scorers', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('number_of_viewers', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('team_home_jersey', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('team_away_jersey', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('broadcasts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('matches', 'uid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('matches', 'is_scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('matches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_matches_external_id'), 'matches', ['external_id'], unique=True)
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_uid'), 'matches', ['uid'], unique=True)
    op.drop_constraint('uq_seasons_external_id', 'seasons', type_='unique')
    op.drop_constraint('uq_seasons_uid', 'seasons', type_='unique')
    op.execute('DROP INDEX IF EXISTS ix_seasons_external_id')
    op.create_index(op.f('ix_seasons_external_id'), 'seasons', ['external_id'], unique=True)
    op.execute('DROP INDEX IF EXISTS ix_seasons_uid')
    op.create_index(op.f('ix_seasons_uid'), 'seasons', ['uid'], unique=True)
    op.alter_column('teams', 'is_partner_team',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('teams', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('teams_external_id_key', 'teams', type_='unique')
    op.drop_constraint('uq_teams_uid', 'teams', type_='unique')
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=True)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_index(op.f('ix_teams_uid'), 'teams', ['uid'], unique=True)
    op.drop_constraint('teams_country_id_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'countries', ['country_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_country_id_fkey', 'teams', 'countries', ['country_id'], ['id'])
    op.drop_index(op.f('ix_teams_uid'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.create_unique_constraint('uq_teams_uid', 'teams', ['uid'])
    op.create_unique_constraint('teams_external_id_key', 'teams', ['external_id'])
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('teams', 'is_partner_team',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_seasons_uid'), table_name='seasons')
    op.create_index('ix_seasons_uid', 'seasons', ['uid'], unique=False)
    op.drop_index(op.f('ix_seasons_external_id'), table_name='seasons')
    op.create_index('ix_seasons_external_id', 'seasons', ['external_id'], unique=False)
    op.create_unique_constraint('uq_seasons_uid', 'seasons', ['uid'])
    op.create_unique_constraint('uq_seasons_external_id', 'seasons', ['external_id'])
    op.drop_index(op.f('ix_matches_uid'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_external_id'), table_name='matches')
    op.alter_column('matches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('matches', 'is_scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('matches', 'uid',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('matches', 'broadcasts')
    op.drop_column('matches', 'team_away_jersey')
    op.drop_column('matches', 'team_home_jersey')
    op.drop_column('matches', 'number_of_viewers')
    op.drop_column('matches', 'number_of_goal_scorers')
    op.drop_column('matches', 'is_kickoff_confirmed')
    op.drop_column('matches', 'localized_title')
    op.drop_column('matches', 'title')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.create_unique_constraint('countries_name_key', 'countries', ['name'])
    op.alter_column('countries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_competitions_uid'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_id'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_external_id'), table_name='competitions')
    op.create_unique_constraint('uq_competitions_uid', 'competitions', ['uid'])
    op.create_unique_constraint('uq_competitions_external_id', 'competitions', ['external_id'])
    op.alter_column('competitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('competitions', 'position',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('competitions', 'hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('competitions', 'has_standings_per_matchday',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_competition_teams_id'), table_name='competition_teams')
    op.alter_column('competition_teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
