"""add_event_type_phase_time_additional

Revision ID: a8beea6414da
Revises: 0001_initial
Create Date: 2026-02-26 13:55:10.159452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8beea6414da'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use IF EXISTS for tables that may not exist on a fresh database
    op.execute('DROP TABLE IF EXISTS player_statistics')
    op.execute('DROP INDEX IF EXISTS idx_lineups_match')
    op.execute('DROP TABLE IF EXISTS lineups')
    op.execute('DROP TABLE IF EXISTS match_statistics')
    op.execute('DROP TABLE IF EXISTS team_leagues')
    op.execute('DROP INDEX IF EXISTS ix_league_seasons_id')
    op.execute('DROP TABLE IF EXISTS league_seasons')
    op.execute('DROP INDEX IF EXISTS ix_leagues_external_id')
    op.execute('DROP INDEX IF EXISTS ix_leagues_id')
    op.execute('DROP TABLE IF EXISTS leagues')
    op.add_column('events', sa.Column('time_additional', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('event_type', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('phase', sa.String(length=50), nullable=True))
    op.execute('DROP INDEX IF EXISTS idx_events_match_id')
    op.execute('DROP INDEX IF EXISTS idx_events_source_id')
    op.execute('DROP INDEX IF EXISTS idx_matches_competition')
    op.execute('DROP INDEX IF EXISTS idx_matches_external_id')
    op.execute('DROP INDEX IF EXISTS idx_matches_matchday')
    op.add_column('standings', sa.Column('match_id', sa.Integer(), nullable=True))
    op.execute('DROP INDEX IF EXISTS idx_standings_lookup')
    op.create_foreign_key(None, 'standings', 'matches', ['match_id'], ['id'], ondelete='SET NULL')
    op.execute('DROP INDEX IF EXISTS idx_teams_external_id')
    op.create_unique_constraint(None, 'teams', ['external_id'])
    op.execute('DROP INDEX IF EXISTS idx_ticker_match')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ticker_match', 'ticker_entries', ['match_id', 'status'], unique=False)
    op.drop_constraint(None, 'teams', type_='unique')
    op.create_index('idx_teams_external_id', 'teams', ['external_id'], unique=True)
    op.drop_constraint(None, 'standings', type_='foreignkey')
    op.create_index('idx_standings_lookup', 'standings', ['season_id', 'competition_id', 'matchday'], unique=False)
    op.drop_column('standings', 'match_id')
    op.create_index('idx_matches_matchday', 'matches', ['competition_id', 'matchday'], unique=False)
    op.create_index('idx_matches_external_id', 'matches', ['external_id'], unique=False)
    op.create_index('idx_matches_competition', 'matches', ['competition_id'], unique=False)
    op.create_index('idx_events_source_id', 'events', ['source_id'], unique=False)
    op.create_index('idx_events_match_id', 'events', ['match_id'], unique=False)
    op.drop_column('events', 'phase')
    op.drop_column('events', 'event_type')
    op.drop_column('events', 'time_additional')
    op.create_table('leagues',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('leagues_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='leagues_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_leagues_id', 'leagues', ['id'], unique=False)
    op.create_index('ix_leagues_external_id', 'leagues', ['external_id'], unique=True)
    op.create_table('league_seasons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_round', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_rounds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rounds', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name='league_seasons_league_id_fkey'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name='league_seasons_season_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='league_seasons_pkey'),
    sa.UniqueConstraint('league_id', 'season_id', name='unique_league_season')
    )
    op.create_index('ix_league_seasons_id', 'league_seasons', ['id'], unique=False)
    op.create_table('team_leagues',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name='team_leagues_league_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='team_leagues_team_id_fkey'),
    sa.PrimaryKeyConstraint('team_id', 'league_id', 'season_year', name='team_leagues_pkey')
    )
    op.create_table('match_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shots_on_goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_off_goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blocked_shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fouls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('corner_kicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('offsides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ball_possession', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yellow_cards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('red_cards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goalkeeper_saves', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_accurate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='match_statistics_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='match_statistics_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='match_statistics_pkey'),
    sa.UniqueConstraint('match_id', 'team_id', name='unique_match_team_stat')
    )
    op.create_table('lineups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('grid', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('formation', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('coach', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('starter', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='lineups_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='lineups_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lineups_pkey')
    )
    op.create_index('idx_lineups_match', 'lineups', ['match_id'], unique=False)
    op.create_table('player_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('goals_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_yellow', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_red', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='player_statistics_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='player_statistics_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='player_statistics_pkey'),
    sa.UniqueConstraint('match_id', 'player_id', name='unique_match_player')
    )
    # ### end Alembic commands ###
