"""add_competition_teams

Revision ID: b0e30d4c15d6
Revises: a8beea6414da
Create Date: 2026-02-26 14:38:12.801811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0e30d4c15d6'
down_revision: Union[str, None] = 'a8beea6414da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'competition_id', 'team_id', name='uq_competition_team')
    )
    op.execute('DROP TABLE IF EXISTS match_statistics')
    op.execute('DROP TABLE IF EXISTS player_statistics')
    op.execute('DROP TABLE IF EXISTS lineups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('grid', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('formation', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('coach', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('starter', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='lineups_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='lineups_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lineups_pkey')
    )
    op.create_table('player_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('goals_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_yellow', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_red', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='player_statistics_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='player_statistics_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='player_statistics_pkey'),
    sa.UniqueConstraint('match_id', 'player_id', name='unique_match_player')
    )
    op.create_table('match_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shots_on_goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_off_goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blocked_shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fouls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('corner_kicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('offsides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ball_possession', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yellow_cards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('red_cards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goalkeeper_saves', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_accurate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='match_statistics_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='match_statistics_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='match_statistics_pkey'),
    sa.UniqueConstraint('match_id', 'team_id', name='unique_match_team_stat')
    )
    op.execute('DROP TABLE IF EXISTS competition_teams')
    # ### end Alembic commands ###
