"""add_synthetic_events_type_index

Revision ID: e6e333f2fb54
Revises: 304c6d16db08
Create Date: 2026-03-19 20:14:58.507746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e333f2fb54'
down_revision: Union[str, None] = '304c6d16db08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_synthetic_events_type', 'synthetic_events', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ix_synthetic_events_type')
    # ### end Alembic commands ###
