"""
Domain Constants
================
Single source of truth for phase mappings used across the application.
"""

from typing import Optional

# Maps synthetic event type strings to their corresponding ticker phase.
# Must be kept in sync with SyntheticEvent types produced by n8n workflows.
SYNTHETIC_EVENT_PHASE_MAP: dict[str, str] = {
    "match_kickoff": "FirstHalf",
    "match_halftime": "FirstHalfBreak",
    "match_second_half": "SecondHalf",
    "match_fulltime": "After",
    "match_extra_kickoff": "ExtraFirstHalf",
    "match_extra_halftime": "ExtraBreak",
    "match_penalties": "PenaltyShootout",
    "match_fulltime_aet": "After",
    "match_fulltime_pen": "After",
}


# Maps Football-API live status codes (short) to internal ticker phase names.
FOOTBALL_API_PHASE_MAP: dict[str, str] = {
    "1H": "FirstHalf",
    "2H": "SecondHalf",
    "HT": "FirstHalfBreak",
    "ET": "SecondHalf",  # extra time – treat as second half for display
    "BT": "FirstHalfBreak",  # break before extra time
    "P": "SecondHalf",
    "FT": "FullTime",
    "AET": "FullTime",
    "PEN": "FullTime",
}


# Human-readable German labels for LLM prompt event types.
EVENT_TYPE_LABEL: dict[str, str] = {
    "goal": "Tor",
    "own_goal": "Eigentor",
    "missed_penalty": "Elfmeter verschossen",
    "yellow_card": "Gelbe Karte",
    "red_card": "Rote Karte",
    "substitution": "Spielerwechsel",
    "kick_off": "Anstoß",
    "halftime": "Halbzeit",
    "fulltime": "Abpfiff",
    "extra_time_start": "Verlängerung beginnt",
    "extra_halftime": "Halbzeitpause Verlängerung",
    "penalty_shootout": "Elfmeterschießen",
    "fulltime_aet": "Abpfiff nach Verlängerung",
    "fulltime_pen": "Abpfiff nach Elfmeterschießen",
    "comment": "Spielszene",
    "pre_match": "Vorbericht",
    "pre_match_prediction": "Spielvorschau & Tipp",
    "pre_match_injuries": "Verletzungsbericht",
    "pre_match_h2h": "Direktvergleich",
    "pre_match_team_stats": "Teamstatistik",
    "pre_match_standings": "Tabellenstand",
    "post_match": "Nachbericht",
    "halftime_comment": "Halbzeitkommentar",
    "live_stats_update": "Live-Statistik-Update",
}

# Human-readable German descriptions for ticker styles.
STYLE_DESC: dict[str, str] = {
    "neutral": "sachlich und neutral – keine Vereinspräferenz",
    "euphorisch": (
        "Du schreibst aus Sicht eines leidenschaftlichen Eintracht-Frankfurt-Fans. "
        "Emotionaler, packender Stil mit kurzen Sätzen, Ausrufen und Dramatik. "
        "Variiere deine Formulierungen — verwende NICHT immer dieselben Phrasen. "
        "Vermeide vor allem die ständige Wiederholung von 'Unfassbar!', 'Die Kurve bebt!', "
        "'Was ist denn hier los?!' oder 'Hoffentlich bringt er frischen Wind!'. "
        "Orientiere dich stattdessen am Stil der STILREFERENZEN weiter unten."
    ),
    "kritisch": "analytisch und kritisch",
}


# Standard 4 match phases generated by generate-match-phases endpoint.
# Each tuple: (event_type, phase, default_minute)
STANDARD_PHASES: list[tuple[str, str, int]] = [
    ("match_kickoff", "FirstHalf", 1),
    ("match_halftime", "FirstHalfBreak", 45),
    ("match_second_half", "SecondHalf", 46),
    ("match_fulltime", "After", 90),
]


# ── Phasen-Sortierung (Backend DB-Reihenfolge) ───────────────
# Primär-Sortkey: Before → After. Phasen die fehlen → Mitte (5).
# Wird von TickerEntryRepository.get_by_match() genutzt.
PHASE_SORT_ORDER: dict[str, int] = {
    "Before": 0,
    "FirstHalf": 1,
    "FirstHalfBreak": 2,
    "SecondHalf": 3,
    "SecondHalfBreak": 4,
    "ExtraFirstHalf": 5,
    "ExtraBreak": 6,
    "ExtraSecondHalf": 7,
    "ExtraSecondHalfBreak": 8,
    "PenaltyShootout": 9,
    "After": 10,
}

# Phasen die einen Spielabschnitt STARTEN → sortieren innerhalb ihrer Minute zuerst
PHASE_START_SET: frozenset[str] = frozenset(
    {
        "FirstHalf",
        "SecondHalf",
        "ExtraFirstHalf",
        "ExtraSecondHalf",
        "PenaltyShootout",
    }
)


# ── Gültige Ticker-Phasen ────────────────────────────────────
# Alle erlaubten Phase-Strings für Ticker-Einträge (Validierung an API-Grenzen).
VALID_PHASES: frozenset[str] = frozenset(
    {
        "Before",
        "PreMatch",
        "FirstHalf",
        "FirstHalfBreak",
        "Halftime",
        "SecondHalf",
        "SecondHalfBreak",
        "ExtraFirstHalf",
        "ExtraBreak",
        "ExtraSecondHalf",
        "ExtraSecondHalfBreak",
        "PenaltyShootout",
        "FullTime",
        "After",
    }
)

# ── LLM-Konfiguration ────────────────────────────────────────
# Single source of truth für alle LLM-Provider-Aufrufe.
LLM_MAX_TOKENS: int = 200
LLM_TEMPERATURE: float = 0.3
LLM_TRANSLATION_TEMPERATURE: float = 0.1
LLM_RETRY_ATTEMPTS: int = 3
LLM_RATE_LIMIT_WAIT_BASE_S: int = 30  # Sekunden; verdoppelt sich pro Attempt

# ── Ticker-Instanzen ─────────────────────────────────────────
DEFAULT_TICKER_INSTANCE: str = "ef_whitelabel"


def resolve_phase(event_type: str) -> Optional[str]:
    """Resolve a synthetic event type string to its ticker phase.

    Args:
        event_type: The synthetic event type (e.g. "match_kickoff", "pre_match_info").

    Returns:
        The corresponding phase string, or None if the event type is unknown.
    """
    if event_type.startswith("pre_match"):
        return "Before"
    if event_type.startswith("post_match"):
        return "After"
    return SYNTHETIC_EVENT_PHASE_MAP.get(event_type)
